### ISSUE TITLE
Page ForumType non fresh can cause Problems

### ISSUE THREAD

**Issue by DanielSchwiperich** [ctsmedia/contao-phpbb-bridge-bundle#38]
Since contao does not know about our forum type it can cause problems if you change a regular page or another page type to forum type because contao saves still the old dca settings which may get parsed by methods which just check if the page is of type regular. 

Maybe also the alias can lead to a problem. We had this on https://www.die-urbane.de where the layout creation was doing a 404.

Todo: test if an alias instead of id the problem:
was not working (but could be dca stuff)
```yml
parameters:
    contao.forum_pageId: '109'
    contao.forum_pageUrl: 'https://www.die-urbane.de/forum.html'
    contao.forum_pageAlias: forum
    contao.forum_groups: ['2']
    contao.url: 'https://www.die-urbane.de'
    contao.body_class: null
    contao.bridge_is_installed: true
```
working
```yml
parameters:
    contao.forum_pageId: '165'
    contao.forum_pageUrl: 'https://www.die-urbane.de/165.html'
    contao.forum_pageAlias: forum
    contao.forum_groups: ['2']
    contao.url: 'https://www.die-urbane.de'
    contao.body_class: null
    contao.bridge_is_installed: true
```
