### ISSUE TITLE
Contao 4.6 private service issue

### ISSUE THREAD

**Issue by MicioMax** [ctsmedia/contao-phpbb-bridge-bundle#47]
On Contao4.6, I get this error : 

`The "phpbb_bridge.connector" service or alias has been removed or inlined when the container was compiled
`
solved patching "/src/Resources/config/services.yml" from
```
services:
    phpbb_bridge.connector:
        class: Ctsmedia\Phpbb\BridgeBundle\PhpBB\Connector
        arguments:
            - "@database_connection"
    phpbb_bridge.event_listener.contao_member_listener:
        class: Ctsmedia\Phpbb\BridgeBundle\EventListener\ContaoMemberListener
        public: true
        arguments:
          - "@phpbb_bridge.connector"
          - "@monolog.logger.contao"

```
to
```
services:
    phpbb_bridge.connector:
        class: Ctsmedia\Phpbb\BridgeBundle\PhpBB\Connector
        public: true
        arguments:
            - "@database_connection"
    phpbb_bridge.event_listener.contao_member_listener:
        class: Ctsmedia\Phpbb\BridgeBundle\EventListener\ContaoMemberListener
        public: true
        arguments:
          - "@phpbb_bridge.connector"
          - "@monolog.logger.contao"

```
So, made the 'phpbb_bridge.connector' service public.
This is a quick and dirty solution, it should be solved by dependency injection, but that's beyond my skills.
